### ISSUE TITLE
Link expired from where the data is fetched

### ISSUE THREAD

**Issue by meticulousCraftman** [cgoldberg/ystockquote#55]
**URLError: <urlopen error [Errno -2] Name or service not known>**

This error is thrown when I try to run the module using python3 IDLE. After analyzing the module I came to know that the link that is being used for fetching data from the Yahoo Finance server has expired i.e. it does not exist anymore. We need to fix the data retrieval part to make the module functional again.

**Comment by cgoldberg** [comment]
Yahoo retired the API
